[workspace]
authors = ["Raghav Mishra <rmis0704@uni.sydney.edu.au>"]
channels = ["conda-forge"]
name = "openarm_can"
platforms = ["linux-64"]
version = "0.1.0"
preview = ["pixi-build"]

[tasks]

[dependencies]
openarm_can = { path = "." }

[package]
name = "openarm_can"
version = "0.1.0"

[package.build]
backend = { name = "pixi-build-cmake", version = "0.*" }

[package.build.config]
extra-args = ["-DCMAKE_BUILD_TYPE=Release"]

[package.host-dependencies]
cmake = "3.20.*"
